version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd /Backed/Akun && npm install && node Index
            - run: cd ../Barang && npm install && node Index
            - run: cd ../Dept && npm install && node Index
            - run: cd ../History && npm install && node Index
            - run: cd ../Logs && npm install
            - run: cd ../Member && npm install && node Index
            - run: cd ../Order && npm install && node Index
            - run: cd ../Profit && npm install && node Index
            - run: cd ../Realtime && npm install && node Index
            - run: cd ../Supplier && npm install && node Index
            - run: cd ../Toko && npm install && node Index
            - run: cd ../Transaksi && npm install && node Index
workflows:
    build-and-test:
      jobs:
        - build-and-test