version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: ls && cd Backend/Akun && npm i && node Index
            - run: ls && cd Backend/Barang && npm i && node Index
            - run: ls && cd Backend/Dept && npm i && node Index
            - run: ls && cd Backend/History && npm i && node Index
            - run: ls && cd Backend/Logs && npm i
            - run: ls && cd Backend/Member && npm i && node Index
            - run: ls && cd Backend/Order && npm i && node Index
            - run: ls && cd Backend/Profit && npm i && node Index
            - run: ls && cd Backend/Realtime && npm i && node Index
            - run: ls && cd Backend/Supplier && npm i && node Index
            - run: ls && cd Backend/Toko && npm i && node Index
            - run: ls && cd Backend/Transaksi && npm i && node Index
workflows:
    build-and-test:
      jobs:
        - build-and-test