version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: ls && cd Backend/Akun && npm i && node Index
            - run: cd /Backed/Barang && npm install && node Index
            - run: cd /Backed/Dept && npm install && node Index
            - run: cd /Backed/History && npm install && node Index
            - run: cd /Backed/Logs && npm install
            - run: cd /Backed/Member && npm install && node Index
            - run: cd /Backed/Order && npm install && node Index
            - run: cd /Backed/Profit && npm install && node Index
            - run: cd /Backed/Realtime && npm install && node Index
            - run: cd /Backed/Supplier && npm install && node Index
            - run: cd /Backed/Toko && npm install && node Index
            - run: cd /Backed/Transaksi && npm install && node Index
workflows:
    build-and-test:
      jobs:
        - build-and-test